apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: phoenix-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phoenix-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50