apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-titan
spec:
  podSelector:
    matchLabels:
      app: titan
  policyTypes:
  - Ingress
  # No "ingress" rules means DENY EVERYTHING