apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: protect-titan
spec:
  podSelector:
    matchLabels:
      app: titan
  policyTypes:
  - Ingress
  ingress:
  # RULE: Allow traffic from the Ingress Controller Namespace
  - from:
    - namespaceSelector:
        matchLabels:
          role: ingress-gateway
    # (Optional) We can be even more specific and ask for the pod label too:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx